// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/onetimepw/onetimepw/domain"
	"github.com/onetimepw/onetimepw/endpoint/web"
	"github.com/onetimepw/onetimepw/gateway/redis"
	"github.com/onetimepw/onetimepw/usecase/api"
)

// Injectors from wire.go:

func InitApp(config domain.Config) (application, error) {
	client, err := redis.NewClient(config)
	if err != nil {
		return application{}, err
	}
	apiAPI := api.New(config, client)
	endpoint, err := web.New(config, client, apiAPI)
	if err != nil {
		return application{}, err
	}
	mainApplication := newApplication(endpoint)
	return mainApplication, nil
}
